version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi_clave_segura
      MYSQL_DATABASE: mi_base
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
